obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.34, -0.34], [-0.34, 0.34], [0.34, 0.34], [0.34, -0.34]]

inflation:
  inflation_radius: 0.3
  cost_scaling_factor: 50

obstacle_2d_layer:
  observation_sources: scan
  scan: {data_type: LaserScan, sensor_frame: base_laser, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 0.5}

voxel_layer:
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 10
  unknown_threshold: 10
  mark_threshold: 0
  footprint_clearing_enabled: true
  publish_voxel_map: true

plugins:
    - {name: static_map, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_2d_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
    - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
