global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  static_map: true
#publish_frequency: 0.5
#transform_tolerance: 1.0
# resolution 0.010
plugins:
    - {name: obstacle_2d_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}

